let providerData = [
    { id: "openai", name: "OpenAI" },
    { id: "anthropic", name: "Anthropic" },
    { id: "groq", name: "Groq" },
    { id: "deepseek", name: "DeepSeek" },
    { id: "minimax", name: "MiniMax" },
    { id: "fireworks", name: "Fireworks" },
    { id: "google", name: "Google Gemini" },
    { id: "openrouter", name: "OpenRouter" },
    { id: "mistral", name: "Mistral" },
    { id: "cloudflare", name: "Cloudflare" },
    { id: "nvidia", name: "NVIDIA NIM" },
    { id: "huggingface", name: "Hugging Face" },
    { id: "xai", name: "xAI" },
    { id: "litellm", name: "LiteLLM Proxy" },
    { id: "qwen", name: "Qwen" },
    { id: "moonshot", name: "Moonshot" },
    { id: "mimo", name: "MiMo" },
    { id: "maritaca", name: "Maritaca" },
    { id: "lmstudio", name: "LM Studio" },
    { id: "local", name: "Local" },
    { id: "ollama", name: "Ollama" }
];
